// <auto-generated />
using Connector.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connector.Infrastructure.Migrations;

[DbContext(typeof(ExportLogDbContext))]
partial class ExportLogDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

        modelBuilder.Entity(
            "Connector.Infrastructure.AppSettingEntity",
            b =>
            {
                b.Property<string>("Key").HasColumnType("TEXT");

                b.Property<string>("Value").IsRequired().HasColumnType("TEXT");

                b.HasKey("Key");

                b.ToTable("AppSetting", (string)null);
            }
        );

        modelBuilder.Entity(
            "Connector.Infrastructure.AuditLogEntry",
            b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                b.Property<string>("Action").IsRequired().HasColumnType("TEXT");

                b.Property<string>("Detail").HasColumnType("TEXT");

                b.Property<string>("Timestamp").IsRequired().HasColumnType("TEXT");

                b.Property<string>("Username").IsRequired().HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Timestamp");

                b.ToTable("AuditLog", (string)null);
            }
        );

        modelBuilder.Entity(
            "Connector.Infrastructure.ExportDefinitionEntity",
            b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                b.Property<int>("ConfigVersion").HasColumnType("INTEGER");

                b.Property<string>("CreatedAt").IsRequired().HasColumnType("TEXT");

                b.Property<string>("CreatedBy").IsRequired().HasColumnType("TEXT");

                b.Property<string>("Description").HasColumnType("TEXT");

                b.Property<bool>("IsEnabled").HasColumnType("INTEGER");

                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");

                b.Property<string>("OutputFormat").IsRequired().HasColumnType("TEXT");

                b.Property<string>("RootNode").IsRequired().HasColumnType("TEXT");

                b.Property<string>("RootTable").IsRequired().HasColumnType("TEXT");

                b.Property<string>("Schedule").HasColumnType("TEXT");

                b.Property<string>("UpdatedAt").HasColumnType("TEXT");

                b.Property<string>("UpdatedBy").HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("ExportDefinition", (string)null);
            }
        );

        modelBuilder.Entity(
            "Connector.Infrastructure.ExportDefinitionRunEntity",
            b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                b.Property<int>("ConfigVersion").HasColumnType("INTEGER");

                b.Property<string>("ErrorMessage").HasColumnType("TEXT");

                b.Property<int>("ExportDefinitionId").HasColumnType("INTEGER");

                b.Property<string>("FinishedAt").HasColumnType("TEXT");

                b.Property<bool>("IsTestRun").HasColumnType("INTEGER");

                b.Property<int>("RecordCount").HasColumnType("INTEGER");

                b.Property<string>("StartedAt").IsRequired().HasColumnType("TEXT");

                b.Property<string>("Status").IsRequired().HasColumnType("TEXT");

                b.Property<string>("TriggeredBy").IsRequired().HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ExportDefinitionId");

                b.ToTable("ExportDefinitionRun", (string)null);
            }
        );

        modelBuilder.Entity(
            "Connector.Infrastructure.ExportRunEntity",
            b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                b.Property<string>("ApprovedBy").HasColumnType("TEXT");

                b.Property<string>("DataFileName").IsRequired().HasColumnType("TEXT");

                b.Property<string>("DeliveredAt").HasColumnType("TEXT");

                b.Property<string>("DeliveredBy").HasColumnType("TEXT");

                b.Property<string>("DeliveryNotes").HasColumnType("TEXT");

                b.Property<string>("ExtractedAt").IsRequired().HasColumnType("TEXT");

                b.Property<int?>("ImportedRecordCount").HasColumnType("INTEGER");

                b.Property<string>("OperatedBy").HasColumnType("TEXT");

                b.Property<int>("RecordCount").HasColumnType("INTEGER");

                b.Property<string>("ReleasedAt").HasColumnType("TEXT");

                b.Property<int>("SequenceNo").HasColumnType("INTEGER");

                b.Property<string>("Sha256").IsRequired().HasColumnType("TEXT");

                b.Property<string>("Status").IsRequired().HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SequenceNo").IsUnique();

                b.ToTable("ExportRun", (string)null);
            }
        );
#pragma warning restore 612, 618
    }
}
